In [2]:
                                         'DATA TRANSFORMATION'

'DATA TRANSFORMATION'

In [3]:
import pandas as pd

df= pd.read_csv("Diab.csv")
print(df)

     Pat_Id  Gender  OGTT  DBP   BMI  Age Diabetic
0       101    Male   176   90  33.7   58      Yes
1       102    Male   150   66  34.7   42       No
2       103    Male    73   50  23.0   21       No
3       104  Female   187   68  37.7   41      Yes
4       105  Female   100   88  46.8   31       No
..      ...     ...   ...  ...   ...  ...      ...
495     596    Male   130   96  22.6   21       No
496     597  Female   111   58  29.5   22       No
497     598  Female    98   60  34.7   22       No
498     599  Female   143   86  30.1   23       No
499     600    Male   121   78  27.8   38       No

[500 rows x 7 columns]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pat_Id    500 non-null    int64
 1   Gender    500 non-null    str
 2   OGTT      500 non-null    int64
 3   DBP       500 non-null    int64
 4   BMI       500 non-null    float64
 5   Age       500 non-null    int64
 6   Diabetic  500 non-null    str
dtypes: float64(1), int64(4), str(2)
memory usage: 27.5 KB

In [5]:
df_cat= df[["Gender",'Diabetic']]
print(df_cat)

     Gender Diabetic
0      Male      Yes
1      Male       No
2      Male       No
3    Female      Yes
4    Female       No
..      ...      ...
495    Male       No
496  Female       No
497  Female       No
498  Female       No
499    Male       No

[500 rows x 2 columns]

In [6]:
df_cont = df.iloc[:,2:6]
print(df_cont)

     OGTT  DBP   BMI  Age
0     176   90  33.7   58
1     150   66  34.7   42
2      73   50  23.0   21
3     187   68  37.7   41
4     100   88  46.8   31
..    ...  ...   ...  ...
495   130   96  22.6   21
496   111   58  29.5   22
497    98   60  34.7   22
498   143   86  30.1   23
499   121   78  27.8   38

[500 rows x 4 columns]

In [7]:
#STANDARDIZATION
# Standardization --> Converting data to have mean = 0 and standard deviation = 1

from sklearn.preprocessing import StandardScaler

SS = StandardScaler()

SS_X = SS.fit_transform(df_cont)

SS_X = pd.DataFrame(SS_X)

SS_X.columns =["OGTT","DBP","BMI","AGE"]

SS_X

         OGTT       DBP       BMI       AGE
0    1.806312  1.512904  0.191222  2.133749
1    0.957604 -0.537564  0.334117  0.769678
2   -1.555878 -1.904543 -1.337752 -1.020667
3    2.165380 -0.366692  0.762801  0.684423
4   -0.674527  1.342031  2.063143 -0.168122
..        ...       ...       ...       ...
495  0.304751  2.025520 -1.394910 -1.020667
496 -0.315458 -1.221054 -0.408936 -0.935412
497 -0.739812 -1.050181  0.334117 -0.935412
498  0.729105  1.171159 -0.323199 -0.850158
499  0.010968  0.487670 -0.651857  0.428660

[500 rows x 4 columns]

In [8]:
#SCALING/ NORMALIZATION
#Scaling/normalization --> Converting data into a fixed range (default: 0 to 1)

from sklearn.preprocessing import MinMaxScaler

MM = MinMaxScaler()

MM_X = MM.fit_transform(df_cont)

MM_X = pd.DataFrame(MM_X)

MM_X.columns = ["OGTT","DBP","BMI","AGE"]

MM_X

         OGTT       DBP       BMI       AGE
0    0.857143  0.652174  0.316973  0.616667
1    0.688312  0.391304  0.337423  0.350000
2    0.188312  0.217391  0.098160  0.000000
3    0.928571  0.413043  0.398773  0.333333
4    0.363636  0.630435  0.584867  0.166667
..        ...       ...       ...       ...
495  0.558442  0.717391  0.089980  0.000000
496  0.435065  0.304348  0.231084  0.016667
497  0.350649  0.326087  0.337423  0.016667
498  0.642857  0.608696  0.243354  0.033333
499  0.500000  0.521739  0.196319  0.283333

[500 rows x 4 columns]

In [9]:
#LABEL ENCODER
#Label Encoder converts categorical text data into numeric labels so machine learning models can process it

from sklearn.preprocessing import LabelEncoder

df_cat = df[["Gender","Diabetic"]].copy()

LE = LabelEncoder()

df_cat["Gender_LE"]=LE.fit_transform(df_cat["Gender"])

df_cat["Diabetic_LE"]=LE.fit_transform(df_cat["Diabetic"])

df_cat.head()

   Gender Diabetic  Gender_LE  Diabetic_LE
0    Male      Yes          1            1
1    Male       No          1            0
2    Male       No          1            0
3  Female      Yes          0            1
4  Female       No          0            0

In [10]:
#ONE HOT ENCODING
#One-Hot Encoding converting categorical values into multiple binary columns (0 and 1)

In [11]:
from sklearn.preprocessing import OneHotEncoder

OHE = OneHotEncoder()

df_g = pd.DataFrame(OHE.fit_transform(df_cat[["Gender"]]).toarray())

df_g.columns = ['Female','Male']

print(df_g)

     Female  Male
0       0.0   1.0
1       0.0   1.0
2       0.0   1.0
3       1.0   0.0
4       1.0   0.0
..      ...   ...
495     0.0   1.0
496     1.0   0.0
497     1.0   0.0
498     1.0   0.0
499     0.0   1.0

[500 rows x 2 columns]

In [12]:
df_d = pd.DataFrame(OHE.fit_transform(df_cat[["Diabetic"]]).toarray())

df_d.columns = ['NO','YES']

df_d

      NO  YES
0    0.0  1.0
1    1.0  0.0
2    1.0  0.0
3    0.0  1.0
4    1.0  0.0
..   ...  ...
495  1.0  0.0
496  1.0  0.0
497  1.0  0.0
498  1.0  0.0
499  1.0  0.0

[500 rows x 2 columns]

In [13]:
# Combine Multiple DataFrames

X = pd.concat([SS_X,df_g,df_d],axis = 1)

X

         OGTT       DBP       BMI       AGE  Female  Male   NO  YES
0    1.806312  1.512904  0.191222  2.133749     0.0   1.0  0.0  1.0
1    0.957604 -0.537564  0.334117  0.769678     0.0   1.0  1.0  0.0
2   -1.555878 -1.904543 -1.337752 -1.020667     0.0   1.0  1.0  0.0
3    2.165380 -0.366692  0.762801  0.684423     1.0   0.0  0.0  1.0
4   -0.674527  1.342031  2.063143 -0.168122     1.0   0.0  1.0  0.0
..        ...       ...       ...       ...     ...   ...  ...  ...
495  0.304751  2.025520 -1.394910 -1.020667     0.0   1.0  1.0  0.0
496 -0.315458 -1.221054 -0.408936 -0.935412     1.0   0.0  1.0  0.0
497 -0.739812 -1.050181  0.334117 -0.935412     1.0   0.0  1.0  0.0
498  0.729105  1.171159 -0.323199 -0.850158     1.0   0.0  1.0  0.0
499  0.010968  0.487670 -0.651857  0.428660     0.0   1.0  1.0  0.0

[500 rows x 8 columns]

In [16]:
# Ordinal Encoding

import pandas as pd

from sklearn.preprocessing import OrdinalEncoder

# Load Dataset

df = pd.read_csv("Diab.csv")
df

     Pat_Id  Gender  OGTT  DBP   BMI  Age Diabetic
0       101    Male   176   90  33.7   58      Yes
1       102    Male   150   66  34.7   42       No
2       103    Male    73   50  23.0   21       No
3       104  Female   187   68  37.7   41      Yes
4       105  Female   100   88  46.8   31       No
..      ...     ...   ...  ...   ...  ...      ...
495     596    Male   130   96  22.6   21       No
496     597  Female   111   58  29.5   22       No
497     598  Female    98   60  34.7   22       No
498     599  Female   143   86  30.1   23       No
499     600    Male   121   78  27.8   38       No

[500 rows x 7 columns]

In [17]:
# Select Categorical Columns (example)

cat_cols = ['Gender','Diabetic']

In [18]:
# Initialize Ordinal Encoder

oe = OrdinalEncoder()

In [19]:
# Apply Ordinal Encoding

df[cat_cols] = oe.fit_transform(df[cat_cols])

In [20]:
# Display Updated Dataset

print(df.head())

   Pat_Id  Gender  OGTT  DBP   BMI  Age  Diabetic
0     101     1.0   176   90  33.7   58       1.0
1     102     1.0   150   66  34.7   42       0.0
2     103     1.0    73   50  23.0   21       0.0
3     104     0.0   187   68  37.7   41       1.0
4     105     0.0   100   88  46.8   31       0.0