In [2]:
import numpy as np
age = np.array([24,28,32,34,36])
age

array([24, 28, 32, 34, 36])

In [3]:
#-----------------------------------------------

In [4]:
import numpy as np
age = np.array([[24],[28],[32],[34],[36]])
age

array([[24],
       [28],
       [32],
       [34],
       [36]])

In [5]:
#---------------------------------------------------

In [6]:
data = np.array([[24,170,84,100],[28,168,80,120],[32,171,75,105],[34,170,78,108],[36,164,80,100]])
data

array([[ 24, 170,  84, 100],
       [ 28, 168,  80, 120],
       [ 32, 171,  75, 105],
       [ 34, 170,  78, 108],
       [ 36, 164,  80, 100]])

In [7]:
# row,column ---Selecting row and column
data [ : , 0:1]   # selecting the age column

array([[24],
       [28],
       [32],
       [34],
       [36]])

In [8]:
np.mean(data[ : , 0:1])
# Calculating the average of a specific column

print("Mean:",np.mean(data[ : , 0:1]))
print("Median:",np.median(data[ : , 0:1]))
print("Standard deviation:",np.std(data[ : , 0:1]))
print("Varience:",np.var(data[ : , 0:1]))

Mean: 30.8
Median: 32.0
Standard deviation: 4.308131845707603
Varience: 18.56

In [9]:
data[ : , 0:2]  # selecting multiple columns

array([[ 24, 170],
       [ 28, 168],
       [ 32, 171],
       [ 34, 170],
       [ 36, 164]])

In [10]:
data[ : , 0:3:2]

array([[24, 84],
       [28, 80],
       [32, 75],
       [34, 78],
       [36, 80]])

In [11]:
# Creating the data in 1D []-1D, [[]]=2D

In [12]:
x1= np.random.randint(10,20,size=6)   #One dimensional array
x1

array([16, 13, 12, 14, 10, 18], dtype=int32)

In [13]:
x1.ndim    #To find out which dimension is it

1

In [14]:
# Creating the data in 2D

In [16]:
x2= np.random.randint(10,20,size=(3,4))   #Two dimensional array
x2

array([[15, 13, 11, 12],
       [17, 13, 17, 15],
       [19, 12, 12, 17]], dtype=int32)

In [17]:
x2.ndim

2

In [18]:
# Creating the data in 3D

In [19]:
x3= np.random.randint(10,20,size=(2,3,4))
x3

array([[[15, 19, 19, 18],
        [12, 18, 11, 15],
        [16, 19, 13, 14]],

       [[13, 17, 12, 15],
        [15, 13, 14, 18],
        [10, 18, 19, 19]]], dtype=int32)

In [20]:
x3.ndim

3

In [21]:
data

array([[ 24, 170,  84, 100],
       [ 28, 168,  80, 120],
       [ 32, 171,  75, 105],
       [ 34, 170,  78, 108],
       [ 36, 164,  80, 100]])

In [22]:
type(data)

numpy.ndarray

In [23]:
#======================================================================================================

In [24]:
#PANDAS- It is a datascience library written in Python,Use to work in Dataset,Displays the data in Tabular format

In [25]:
data

array([[ 24, 170,  84, 100],
       [ 28, 168,  80, 120],
       [ 32, 171,  75, 105],
       [ 34, 170,  78, 108],
       [ 36, 164,  80, 100]])

In [26]:
import pandas as pd
df = pd.DataFrame(data)
df

    0    1   2    3
0  24  170  84  100
1  28  168  80  120
2  32  171  75  105
3  34  170  78  108
4  36  164  80  100

In [27]:
type(df)

pandas.DataFrame

In [28]:
df.columns=["Age","Height","Weight","BP"]
df

   Age  Height  Weight   BP
0   24     170      84  100
1   28     168      80  120
2   32     171      75  105
3   34     170      78  108
4   36     164      80  100

In [30]:
df.index=["a","b","c","d","e"]
df

   Age  Height  Weight   BP
a   24     170      84  100
b   28     168      80  120
c   32     171      75  105
d   34     170      78  108
e   36     164      80  100

In [31]:
print("Mean:", df["BP"].mean())
print("Median:",df["BP"].median())
print("Mode:",df["BP"].mode())
print("standard deviation:",df["BP"].std())
print("Variance:",df["BP"].var())

Mean: 106.6
Median: 105.0
Mode: 0    100
Name: BP, dtype: int64
standard deviation: 8.23407554009556
Variance: 67.8

In [32]:
df["BP"].describe()

count      5.000000
mean     106.600000
std        8.234076
min      100.000000
25%      100.000000
50%      105.000000
75%      108.000000
max      120.000000
Name: BP, dtype: float64