In [2]:
import pandas as pd

df1 = pd.read_csv('first_file.csv')

df1

    Id   Age  Height  Weight
0  101  24.0     175      85
1  102  25.0     165      72
2  103  30.0     168      75
3  104   NaN     172      79
4  105  28.0     170      76

In [3]:
df2 = pd.read_csv('second_file.csv')

df2

    Id  Age  Height  Weight
0  201   24     178      67
1  202   23     170      76
2  203   22     168      80
3  204   21     165      81
4  205   26     171      82

In [5]:
df3 = pd.read_csv('third_file.csv')

df3

  Gender   BP
0      M  120
1      F  140
2      M  145
3      F  132
4      M  130
5      F  150
6      M  147
7      F  132
8      M  128
9      F  130

In [6]:
df1

    Id   Age  Height  Weight
0  101  24.0     175      85
1  102  25.0     165      72
2  103  30.0     168      75
3  104   NaN     172      79
4  105  28.0     170      76

In [8]:
int(df1['Age'].mean())

26

In [10]:
df1['Age']=df1['Age'].fillna(int(df1['Age'].mean()))

In [11]:
df1

    Id   Age  Height  Weight
0  101  24.0     175      85
1  102  25.0     165      72
2  103  30.0     168      75
3  104  26.0     172      79
4  105  28.0     170      76

In [12]:
#let's see what's their in df2

In [13]:
df2

    Id  Age  Height  Weight
0  201   24     178      67
1  202   23     170      76
2  203   22     168      80
3  204   21     165      81
4  205   26     171      82

In [14]:
#Two different files but variables looks like the same.
#rows concatinating

In [15]:
df4 = pd.concat([df1,df2],ignore_index=True)

In [16]:
df4

    Id   Age  Height  Weight
0  101  24.0     175      85
1  102  25.0     165      72
2  103  30.0     168      75
3  104  26.0     172      79
4  105  28.0     170      76
5  201  24.0     178      67
6  202  23.0     170      76
7  203  22.0     168      80
8  204  21.0     165      81
9  205  26.0     171      82

In [17]:
# let's see what's their in df3

In [18]:
df3

  Gender   BP
0      M  120
1      F  140
2      M  145
3      F  132
4      M  130
5      F  150
6      M  147
7      F  132
8      M  128
9      F  130

In [19]:
#looks like variables are different in both df3 and df4, but rows are same
# columns concatinating

In [21]:
df5 = pd.concat([df4,df3],axis=1)

df5

In [22]:
df5

    Id   Age  Height  Weight Gender   BP
0  101  24.0     175      85      M  120
1  102  25.0     165      72      F  140
2  103  30.0     168      75      M  145
3  104  26.0     172      79      F  132
4  105  28.0     170      76      M  130
5  201  24.0     178      67      F  150
6  202  23.0     170      76      M  147
7  203  22.0     168      80      F  132
8  204  21.0     165      81      M  128
9  205  26.0     171      82      F  130

In [23]:
#groupby

In [24]:
df5['Age'].mean()

np.float64(24.9)

In [26]:
"""How can we calculate the separate means for both Male and Female individually
---Using Groupby"""

'How can we calculate the separate means for both Male and Female individually\n---Using Groupby'

In [25]:
df5.groupby("Gender")["Age"].mean()

Gender
F    24.6
M    25.2
Name: Age, dtype: float64